# 로컬에서 NAS MySQL(my_new_project_db) 연결
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://125.141.20.218:3306/my_new_project_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: hyunchang88
    password: gusckd88!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: false
